services:
  backend:
    build: ./backend         # points to the backend folder where Dockerfile lives
    container_name: travel-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: travel-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: travel
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
