"""update tables

Revision ID: 42b865715a52
Revises: a4b50399d556
Create Date: 2025-09-18 15:47:17.407282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42b865715a52'
down_revision: Union[str, Sequence[str], None] = 'a4b50399d556'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('quota', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_id'), 'subscription', ['id'], unique=False)
    op.add_column('users', sa.Column('role', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('approved', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('subscriptionId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'subscription', ['subscriptionId'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'subscriptionId')
    op.drop_column('users', 'approved')
    op.drop_column('users', 'role')
    op.drop_index(op.f('ix_subscription_id'), table_name='subscription')
    op.drop_table('subscription')
    # ### end Alembic commands ###
